services:
  server:
    hostname: exospace
    image: itzg/minecraft-server:java21
    container_name: exospace
    ports:
    - '25565:25565'
    environment:
      SEED: 0
      ICON: https://avatars.githubusercontent.com/u/175053991?s=200&v=4
      VERSION: '1.21.1'
      EULA: 'TRUE'
      USE_AIKAR_FLAGS: true
      NEOFORGE_VERSION: '21.1.194'
      VIEW_DISTANCE: 8
      MODE: survival
      DIFFICULTY: hard
      ALLOW_FLIGHT: true
      ONLINE_MODE: false
      MODRINTH_MODPACK: /data/modpack.mrpack
      MEMORY: '16G'
      RCON_CMDS_FIRST_CONNECT: |
        /whitelist off
        /op mxxntype
      MOTD: invar-server/0.6.0 | exospace | 1.21.1
      ENABLE_AUTOPAUSE: false
      MAX_PLAYERS: 8
      TYPE: MODRINTH
    restart: on-failure
    volumes:
    - source: server
      target: /data
      type: bind
    - source: export/exospace-latest.mrpack
      target: /data/modpack.mrpack
      type: bind
      read_only: true
