id: forge-config-api-port
category: mod
tags:
  main: null
  others: []
environment:
  client: required
  server: required
source: !Remote
  download_url: https://cdn.modrinth.com/data/ohNO6lps/versions/e5mORIZw/ForgeConfigAPIPort-v21.1.4-1.21.1-NeoForge.jar
  file_name: ForgeConfigAPIPort-v21.1.4-1.21.1-NeoForge.jar
  file_size: 104575
  version_id: e5mORIZw
  hashes:
    sha1: '6eb383b62e680deb6c6955552759b1be81a1973d'
    sha512: '2ffab30cde96341ac463168d457aea6eecf122baa3d8bb1e6d8db56070c8b090590da2c9570855481b9829ac1351d950582589c01c1056a8a9968ce45eb50cd3'
