id: resourceful-config
category: mod
tags:
  main: null
  others: []
environment:
  client: required
  server: required
source: !Remote
  download_url: https://cdn.modrinth.com/data/M1953qlQ/versions/lSbyRD6v/resourcefulconfig-neoforge-1.21-3.0.11.jar
  file_name: resourcefulconfig-neoforge-1.21-3.0.11.jar
  file_size: 341009
  version_id: lSbyRD6v
  hashes:
    sha1: '6bf2b6ea9c071c00a2abcdc552667fb6f7d21031'
    sha512: '8e4ccc37732b3f5190e7e98df34dbc1339fe614494fcabf1aeaeab9ad8e5993522964b51be31882000c08c48a6d0096b5458364415bb81f2b2b775a7daf2eb87'
